Alexander/frontend/nefi-74-v2
developerUruit/all-in-one-inbox pull request #18
Opened 2022-09-05 20:00 UTC by AlexanderPineda

# Description
New components created for chat view for chat component used in Home page and others.

# Main Changes
- Filter button added for topbar component.
- contextual menu added for dots icons in chatcards

### Interfaces Added

- Button Filter
<img width="531" alt="imagen" src="https://user-images.githubusercontent.com/59176307/188507600-e20a397a-7b24-4dcd-a322-b06286cc22c1.png">

<img width="597" alt="imagen" src="https://user-images.githubusercontent.com/59176307/188507649-63ef20c2-aa3f-4ec8-8c96-31335e9acd0f.png">

- Contextual Menu for dots in chatcards
<img width="785" alt="imagen" src="https://user-images.githubusercontent.com/59176307/188507674-3788acac-bac1-4680-b470-6abd92afde5a.png">

2022-09-05 20:57 UTC, alphonse92 requested changes

2022-09-05 20:57 UTC, alphonse92 commented on client/src/components/Chat/ChatCard.js
> +import { useTheme } from '@mui/material/styles';
The .prettierrc file has a rule called: `bracketSpacing` which is equals to `false`, your prettier is not taking that `.prettierrc` into count. It may be caused because you are opening `all in one inbox` project as working directory in vscode. So, please run prettier again and make sure your IDE is using the prettier rules configured for client

2022-09-05 20:57 UTC, alphonse92 commented on client/src/components/Chat/ChatCard.js
> +import { useTheme } from '@mui/material/styles';
It should result in not changing this line, it should be `import {useTheme} from '@mui/material/styles';`

2022-09-05 20:57 UTC, alphonse92 commented on client/src/components/Chat/ChatCard.js
> +          <ChatCardsDots />
Separe it as general-ussage component. It'should be called "ThreeDots" and it should receive a parameters to place the three dots vertically or horizontally

2022-09-05 20:57 UTC, alphonse92 commented on client/src/components/FilterBtn/index.js
> +        id="demo-positioned-menu"
AGAIN, do NOT copy and paste without adjust the all stuff

2022-09-05 20:57 UTC, alphonse92 commented on client/src/components/FilterBtn/index.js
> +        aria-labelledby="demo-positioned-button"
Adjust or remove this

2022-09-05 20:57 UTC, alphonse92 commented on client/src/components/FilterBtn/index.js
> +export default function FilterBtn() {
We are calling Buttons as `Button` not "Btn"

2022-09-05 20:57 UTC, alphonse92 commented on client/src/components/FilterBtn/index.js
> +export default function FilterBtn() {
Lets rename it as `FillterMenuButton`

2022-09-05 20:57 UTC, alphonse92 commented on client/src/components/FilterBtn/index.js
> +        id="demo-positioned-button"
AGAIN, do NOT copy and paste without adjust the all stuff

2022-09-05 20:57 UTC, alphonse92 commented on client/src/components/FilterBtn/index.js
> +        aria-controls={open ? 'demo-positioned-menu' : undefined}
AGAIN, do NOT copy and paste without adjust the all stuff

2022-09-05 20:57 UTC, alphonse92 commented on client/src/components/FilterBtn/index.js
> +        <MenuItem className={classes.menuItemTitle} disabled>Filters <Funnel size={22} /></MenuItem>
This button is not reusable. Let's allow this component to receive the menu items as children. Mainly, this button just toggle the popeable menu. That's all

2022-09-05 20:57 UTC, alphonse92 commented on client/src/components/FilterBtn/index.js
> +          <Button className={classes.secondaryButton} variant="text">Reset Filters</Button>
we ALREADY HAVE a button component that already implements the logic to use the theme and the other project stuff. Replace this button

2022-09-05 20:57 UTC, alphonse92 commented on client/src/components/FilterBtn/styles.js
> +    secondaryButton: {
Not required, we already have a custom button with this kinda configs

2022-09-05 20:57 UTC, alphonse92 commented on client/src/configs/theme.js
> +          text: {
what is the purpose of this one?

2022-09-05 23:05 UTC, alphonse92 requested changes

2022-09-05 23:05 UTC, alphonse92 commented on client/src/components/ChatCardsDots/index.js
> +          sx: {
make it as class

2022-09-05 23:05 UTC, alphonse92 commented on client/src/components/FilterBtn/index.js
> +        <MenuItem className={classes.menuItem}><Checkbox />Email</MenuItem>
Let's create a component called "MenuButtonChildContainer" which will position its children, instead of setting classes.menuItem in all of the MenuButton children

2022-09-06 02:35 UTC, AlexanderPineda commented on client/src/components/Chat/ChatCard.js
> +import { useTheme } from '@mui/material/styles';
I already configured the code editor and the changes were successfull tested in my editor.

2022-09-06 14:48 UTC, AlexanderPineda commented on client/src/components/Chat/ChatCard.js
> +          <ChatCardsDots />
Name component changed

2022-09-06 14:50 UTC, AlexanderPineda commented on client/src/components/Chat/ChatCard.js
> +          <ChatCardsDots />
properties of usability vertical and horizontal orientation added

2022-09-06 14:51 UTC, AlexanderPineda commented on client/src/components/FilterBtn/index.js
> +        id="demo-positioned-menu"
name of id and area-label-control changed

2022-09-06 14:52 UTC, AlexanderPineda commented on client/src/components/FilterBtn/index.js
> +        aria-labelledby="demo-positioned-button"
done

2022-09-06 14:59 UTC, AlexanderPineda commented on client/src/components/FilterBtn/index.js
> +export default function FilterBtn() {
renamed

2022-09-06 15:00 UTC, AlexanderPineda commented on client/src/components/FilterBtn/index.js
> +        aria-controls={open ? 'demo-positioned-menu' : undefined}
done

2022-09-06 15:39 UTC, AlexanderPineda commented on client/src/components/FilterBtn/styles.js
> +    secondaryButton: {
done

2022-09-06 16:02 UTC, AlexanderPineda commented on client/src/components/ChatCardsDots/index.js
> +          sx: {
done

2022-09-06 16:20 UTC, AlexanderPineda commented on client/src/components/FilterBtn/index.js
> +        <MenuItem className={classes.menuItem}><Checkbox />Email</MenuItem>
done

2022-09-06 18:09 UTC, alphonse92 requested changes

2022-09-06 18:09 UTC, alphonse92 commented on client/src/components/MenuButton/index.js
> +        aria-controls={open ? 'positionedMenu' : undefined}
receive button props by spreading props from `MenuButton`

2022-09-06 18:09 UTC, alphonse92 commented on client/src/components/ThreeDots/index.js
> +          aria-controls={open ? 'account-menu' : undefined}
Same as MenuButton, remove all fixed props and receive it by spreading props

2022-09-06 18:09 UTC, alphonse92 commented on client/src/components/ThreeDots/index.js
> +        id="account-menu"
same here, remove fixed props

2022-09-06 18:09 UTC, alphonse92 commented on client/src/mocks/temporal.js
>  const chatsData = {
This file SHOULD be removed, we already using the API, it's not longer used!

2022-09-06 18:25 UTC, AlexanderPineda commented on client/src/mocks/temporal.js
>  const chatsData = {
done

2022-09-06 18:26 UTC, AlexanderPineda commented on client/src/components/MenuButtonChildContainer/index.js
> +export default function ThreeDots({orientation, menuItem}) {
done

2022-09-06 19:37 UTC, alphonse92 requested changes

2022-09-06 19:37 UTC, alphonse92 commented on client/src/components/Chat/ChatCard.js
> +          <ThreeDots orientation="vertical" menuItems={['Add client', 'Assign conversation', 'Block conversation', 'Send to trash']} />
Rename it as ThreeDots Menu

2022-09-06 19:37 UTC, alphonse92 commented on client/src/components/ThreeDots/index.js
> +export default function ThreeDots({orientation, menuItems}) {
Rename it as well the module filename: ThreeDotsMenu.

2022-09-06 19:37 UTC, alphonse92 commented on client/src/components/MenuButtonChildContainer/index.js
> +export default function MeuButtonChildContainer() {
Typo error: Meu instead of Menu

2022-09-06 19:37 UTC, alphonse92 commented on client/src/hooks/conversations/unassignInbox/provider.js
> +    {value: {...contextData}},
Great!

2022-09-06 19:43 UTC, AlexanderPineda commented on client/src/components/Chat/ChatCard.js
> +          <ThreeDots orientation="vertical" menuItems={['Add client', 'Assign conversation', 'Block conversation', 'Send to trash']} />
done

2022-09-06 19:44 UTC, AlexanderPineda commented on client/src/components/MenuButtonChildContainer/index.js
> +export default function MeuButtonChildContainer() {
done

2022-09-06 19:44 UTC, AlexanderPineda commented on client/src/hooks/conversations/unassignInbox/provider.js
> +    {value: {...contextData}},
done

2022-09-06 19:57 UTC, alphonse92 requested changes
Just one more change and we will be done

2022-09-06 19:57 UTC, alphonse92 commented on client/src/components/MenuButton/index.js
> +        {...MenuProps}
props should had be spread at the end, to allow deep customization

2022-09-06 20:06 UTC, alphonse92 approved these changes
LGTM

2022-09-06 20:07 UTC, merged