NEFI-83 UI clients and Client provider and others
developerUruit/all-in-one-inbox pull request #28
Opened 2022-09-08 01:46 UTC by AlexanderPineda

2022-09-08 15:22 UTC, alphonse92 requested changes

2022-09-08 15:22 UTC, alphonse92 commented on client/src/components/forms/FormModalAddClient/index.js
> +  // const {handleSubmit} = useForm();
remove comments

2022-09-08 15:22 UTC, alphonse92 commented on client/src/hooks/clients/provider.js
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
don't disable

2022-09-08 15:22 UTC, alphonse92 commented on client/src/hooks/user/Login/provider.js
>    }, []);
dont disable

2022-09-08 15:22 UTC, alphonse92 commented on client/src/services/clients.js
> +export const getClientsList = async () => {
That data will be paginated. Please use the conversations paginator features to know how to do that. And talk with camilo

2022-09-08 16:46 UTC, AlexanderPineda commented on client/src/components/TableContactManagement/index.js
> +                <TableCell align="center">{row.name}</TableCell>
done

2022-09-08 16:46 UTC, AlexanderPineda commented on client/src/pages/dashboard/contactManagement/Clients/index.js
> +              <Button
done

2022-09-08 16:46 UTC, AlexanderPineda commented on client/src/components/forms/FormModalAddClient/index.js
> +  // const {handleSubmit} = useForm();
done

2022-09-08 16:47 UTC, AlexanderPineda commented on client/src/hooks/clients/provider.js
> +  // eslint-disable-next-line react-hooks/exhaustive-deps
done

2022-09-08 16:48 UTC, AlexanderPineda commented on client/src/hooks/user/Login/provider.js
>    }, []);
done

2022-09-09 05:14 UTC, AlexanderPineda commented on client/src/components/TableContactManagement/index.js
> +                <TableCell align="center">{row.name}</TableCell>
done

2022-09-09 05:15 UTC, AlexanderPineda commented on client/src/services/clients.js
> +export const getClientsList = async () => {
done

2022-09-09 14:51 UTC, alphonse92 requested changes

2022-09-09 14:51 UTC, alphonse92 commented on client/src/pages/dashboard/contactManagement/Clients/index.js
> +          <Modal
Move the line 33 to 45 to a new component, that is why I did mean with move out the implementation.

2022-09-09 14:51 UTC, alphonse92 commented on client/src/pages/dashboard/contactManagement/styles.js
> +      padding: '40px 70px 40px 40px',
No paddign without spacing. 70px = theme.spacing(9). theme.spacing(1)="8px" do the maths.

2022-09-09 14:51 UTC, alphonse92 commented on client/src/pages/dashboard/contactManagement/styles.js
> +      padding: '40px 70px 40px 40px',
40px = theme.spacing(5)

2022-09-09 14:51 UTC, alphonse92 commented on client/src/hooks/clients/provider.js
> +export default function UserLoginProvider({children}) {
Rename this component

2022-09-09 14:51 UTC, alphonse92 commented on client/src/hooks/clients/provider.js
> +export default function UserLoginProvider({children}) {
CustomerManagementProvider

2022-09-09 14:51 UTC, alphonse92 commented on client/src/components/custom/Paginator/index.js
> +            previous: props => <button {...props}>Previous</button>,
style the buttons. Variants text

2022-09-09 14:51 UTC, alphonse92 commented on client/src/pages/dashboard/contactManagement/Clients/styles.js
> +  {name: 'clients'},
contact-management-customers

2022-09-09 14:51 UTC, alphonse92 commented on client/src/hooks/clients/provider.js
> +  const {nextPage} = LoadClientsGeneratorHook({page: 0, limit: 10});
LoadCustomersGeneratorHook

2022-09-09 14:51 UTC, alphonse92 commented on client/src/hooks/clients/LoadClientsGeneratorHook.js
> +export default function LoadClientsGeneratorHook(...props) {
Rename it to LoadCustomersGeneratorHook as well the module

2022-09-09 15:20 UTC, AlexanderPineda commented on client/src/pages/dashboard/contactManagement/Clients/index.js
> +          <Modal
done

2022-09-09 15:32 UTC, AlexanderPineda commented on client/src/hooks/clients/provider.js
> +export default function UserLoginProvider({children}) {
done

2022-09-09 15:35 UTC, AlexanderPineda commented on client/src/pages/dashboard/contactManagement/Clients/styles.js
> +  {name: 'clients'},
done

2022-09-09 15:40 UTC, AlexanderPineda commented on client/src/hooks/clients/LoadClientsGeneratorHook.js
> +export default function LoadClientsGeneratorHook(...props) {
done

2022-09-09 16:11 UTC, AlexanderPineda commented on client/src/components/custom/Paginator/index.js
> +            previous: props => <button {...props}>Previous</button>,
done

2022-09-09 17:08 UTC, alphonse92 commented on client/src/components/ThreeDotsMenu/index.js
> +export default function ThreeDotsMenu({orientation, menuItems, menuLocation}) {
Great

2022-09-09 17:10 UTC, alphonse92 commented on client/src/components/forms/FormModalAddClient/index.js
> +              {...register('phone', {
Thanks for doing this job

2022-09-09 17:22 UTC, alphonse92 requested changes

2022-09-09 17:22 UTC, alphonse92 commented on client/src/components/TableContactManagement/styles.js
> +        height: '40px'
As I said: NOT fixed heights. Use paddings instead. Set a maxHeight if you want. Padding should be top: theme.spacing(2.5) and bottom: theme.spacing(2.5) + fontSize. maxHeight: theme.spacing(5)

2022-09-09 17:22 UTC, alphonse92 commented on client/src/components/TableContactManagement/styles.js
> +      paddingTop: '20px'
paddingTop: theme.spacing(2.5)  (that is 20px)

2022-09-09 17:22 UTC, alphonse92 commented on client/src/components/forms/FormModalAddClient/styles.js
> +      width: '170px',
Please remove that. Not fixed widths. If you need to set widths, please use it's parent container and use percentual widths.

2022-09-09 17:22 UTC, alphonse92 commented on client/src/hooks/clients/LoadCustomersGeneratorHook.js
> +  return RequestGeneratorHook(url, ...props);
You have to pull development and update with development. the second parameter of RequestGeneratorHook for this case is undefined

To update with development commit all your changes and :

```

git checkout development
git pull
git checkout $your_branch_here
git merge development

````


After that you should resolve conflicts. Resolve and commit the resolution

2022-09-09 17:22 UTC, alphonse92 commented on client/src/hooks/clients/use.js
> +    clients,
customers

2022-09-09 17:22 UTC, alphonse92 commented on client/src/hooks/clients/provider.js
> +    clients,
customers

2022-09-09 17:22 UTC, alphonse92 commented on client/src/hooks/clients/provider.js
> +  const [clients, setclients] = useState();
customers

2022-09-09 17:28 UTC, AlexanderPineda commented on client/src/components/ThreeDotsMenu/index.js
> +export default function ThreeDotsMenu({orientation, menuItems, menuLocation}) {
check

2022-09-09 17:45 UTC, AlexanderPineda commented on client/src/components/TableContactManagement/styles.js
> +        height: '40px'
maxHeight propperty does not have any effect in the row, the theme spacing has a similar effect comparing with the previous values with theme.spacing(0.3)

2022-09-09 17:46 UTC, AlexanderPineda commented on client/src/components/TableContactManagement/styles.js
> +        height: '40px'
the height propperty was dropped according the requirement

2022-09-09 17:47 UTC, AlexanderPineda commented on client/src/components/TableContactManagement/styles.js
> +      paddingTop: '20px'
already done

2022-09-09 18:42 UTC, AlexanderPineda commented on client/src/components/forms/FormModalAddClient/styles.js
> +      width: '170px',
done

2022-09-09 18:42 UTC, AlexanderPineda commented on client/src/hooks/clients/LoadCustomersGeneratorHook.js
> +  return RequestGeneratorHook(url, ...props);
already merged

2022-09-09 18:48 UTC, AlexanderPineda commented on client/src/hooks/clients/use.js
> +    clients,
done

2022-09-09 18:49 UTC, AlexanderPineda commented on client/src/hooks/clients/provider.js
> +    clients,
done

2022-09-09 18:49 UTC, AlexanderPineda commented on client/src/hooks/clients/provider.js
> +  const [clients, setclients] = useState();
done

2022-09-09 21:23 UTC, alphonse92 approved these changes

2022-09-09 21:43 UTC, merged