NEFI-98: new refactorization of dialog reusable component
developerUruit/all-in-one-inbox pull request #48
Opened 2022-09-14 21:08 UTC by AlexanderPineda

# Description
Version two of dialog modal reusable component.

# Main Changes
- Creation of new component to handle dialog messages for project
- Implementation of the component in the proposed location in the table 

## Previews
<img width="1393" alt="imagen" src="https://user-images.githubusercontent.com/59176307/190262708-3cd30f1c-1c69-4491-9725-f4fb0c8241a8.png">

2022-09-14 21:37 UTC, alphonse92 requested changes

2022-09-14 21:37 UTC, alphonse92 commented on client/src/components/TableContactManagement/index.js
> +        primary: {text: 'Accept', callback: 'test'},
and the callbacks are...?

2022-09-14 21:37 UTC, alphonse92 commented on client/src/components/ThreeDotsMenu/index.js
> +            {menuItemText}
nice, but just call it text

2022-09-14 21:37 UTC, alphonse92 commented on client/src/components/TableContactManagement/index.js
> +  {menuItemText: 'Re-assign'},
Lets the menu item be:

```
{
  text: "Delete Client",
  dialog:{
     "title": "Delete confirmation dialog",
     ...
  }
}
```

2022-09-14 21:37 UTC, alphonse92 commented on client/src/components/TableContactManagement/index.js
> +const menuItems = [
If you want to set callbacks in the menu items payload, you should declare this array inside the component

2022-09-14 21:37 UTC, alphonse92 requested changes

2022-09-14 21:37 UTC, alphonse92 commented on client/src/components/TableContactManagement/index.js
> +        primary: {text: 'Accept', callback: 'test'},
You should declare this array inside the component in order to set the proper callback

2022-09-14 21:39 UTC, alphonse92 requested changes

2022-09-14 21:39 UTC, alphonse92 commented on client/src/components/TableContactManagement/index.js
> +        primary: {text: 'Accept', callback: 'test'},
For now the callback for accept button should be console.log, as well the other button

2022-09-14 21:41 UTC, alphonse92 requested changes

2022-09-14 21:41 UTC, alphonse92 commented on client/src/components/custom/Dialog/index.js
> +        <Button variant="text" onClick={handleClose}>
remember what we told about this: the dialog actions will receive the children as props from DialogModal. 

In the other hand, the DialogModal should receive 3 props: text, title, and buttons. Text and title are strings, but buttons is an array of components, y this case, buttons. You only need that props

2022-09-14 21:47 UTC, AlexanderPineda commented on client/src/components/TableContactManagement/index.js
> +        primary: {text: 'Accept', callback: 'test'},
done

2022-09-14 21:47 UTC, AlexanderPineda commented on client/src/components/ThreeDotsMenu/index.js
> +            {menuItemText}
done

2022-09-14 21:47 UTC, AlexanderPineda commented on client/src/components/TableContactManagement/index.js
> +  {menuItemText: 'Re-assign'},
done

2022-09-14 21:48 UTC, AlexanderPineda commented on client/src/components/TableContactManagement/index.js
> +const menuItems = [
done

2022-09-14 22:41 UTC, AlexanderPineda commented on client/src/components/custom/Dialog/index.js
> +        <Button variant="text" onClick={handleClose}>
done

2022-09-14 22:47 UTC, alphonse92 requested changes

2022-09-14 22:47 UTC, alphonse92 commented on client/src/components/ThreeDotsMenu/index.js
> +      onChangeSelectedItem({open: true, ...dialog});
to open or close the dialog is not the concern of the ThreeDots menu, the same for dialog, the only thing you should do is send the option the user selected.

2022-09-14 22:47 UTC, alphonse92 commented on client/src/components/ThreeDotsMenu/index.js
> +            onClick={() => handleClickMenuItem(dialog)}>
Rename! Pay attention to details, isn't dialog, replace with: 
```
<MenuItem
            key={text}
            onClick={() => handleClickMenuItem(option)}>
```

2022-09-14 22:47 UTC, alphonse92 commented on client/src/components/ThreeDotsMenu/index.js
> +        {menuItems.map(({text, dialog}) => (
instead of `{menuItems.map(({text, dialog}) => (`

replace with `{menuItems.map((option) => (`

2022-09-14 22:47 UTC, alphonse92 commented on client/src/components/ThreeDotsMenu/index.js
> +    if (dialog) {
Not dialog

2022-09-14 22:47 UTC, alphonse92 commented on client/src/components/ThreeDotsMenu/index.js
> +  const handleClickMenuItem = dialog => {
isnt dialog

2022-09-14 22:47 UTC, alphonse92 commented on client/src/components/TableContactManagement/index.js
> +        <Dialog
Move this implementation to another module called ConfirmCancelDialog.js (that is the objective of the ticket). After the user clics on the option and the option is "delete customer" show that dialog. Yes, you will need the dialogState to show the proper dialog

2022-09-15 00:02 UTC, AlexanderPineda commented on client/src/components/ThreeDotsMenu/index.js
> +      onChangeSelectedItem({open: true, ...dialog});
Done, I dropped the stateSetter out of that component the same for the dialog component delegating the responsibility to the corcerned components

2022-09-15 00:03 UTC, AlexanderPineda commented on client/src/components/ThreeDotsMenu/index.js
> +            onClick={() => handleClickMenuItem(dialog)}>
renamed

2022-09-15 00:03 UTC, AlexanderPineda commented on client/src/components/ThreeDotsMenu/index.js
> +        {menuItems.map(({text, dialog}) => (
changed

2022-09-15 00:04 UTC, AlexanderPineda commented on client/src/components/ThreeDotsMenu/index.js
> +    if (dialog) {
renamed

2022-09-15 00:04 UTC, AlexanderPineda commented on client/src/components/ThreeDotsMenu/index.js
> +  const handleClickMenuItem = dialog => {
renamed

2022-09-15 00:10 UTC, AlexanderPineda commented on client/src/components/TableContactManagement/index.js
> +        <Dialog
done

2022-09-15 19:40 UTC, alphonse92 approved these changes

2022-09-15 19:41 UTC, merged